import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "WINWIN",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon/logo.svg" />
        <meta name="theme-color" content="#edff08" />
      </head>
      <body className={inter.className}>
        {children}
        <div className="h-[5rem]"></div>
      </body>
    </html>
  );
}
